/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project2;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Soal2 extends javax.swing.JFrame {

    /**
     * Creates new form Soal2
     */
    public Soal2() {
        initComponents();
        tfJumlahPesan.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMenu = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NasiGoreng = new javax.swing.JRadioButton();
        EsTeh = new javax.swing.JRadioButton();
        NasiKuning = new javax.swing.JRadioButton();
        EsJeruk = new javax.swing.JRadioButton();
        MieAyam = new javax.swing.JRadioButton();
        Chocolate = new javax.swing.JRadioButton();
        AyamGeprek = new javax.swing.JRadioButton();
        CookiesOreo = new javax.swing.JRadioButton();
        KentangGoreng = new javax.swing.JRadioButton();
        CirengCrispy = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        tfJumlahPesan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfPesanan = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        tfJumlah = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 70, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WARUNG JOYFUL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, 30));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, 30));

        btMenu.add(NasiGoreng);
        NasiGoreng.setText("Nasi Goreng");
        NasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NasiGorengActionPerformed(evt);
            }
        });
        getContentPane().add(NasiGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        btMenu.add(EsTeh);
        EsTeh.setText("Es Teh");
        getContentPane().add(EsTeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        btMenu.add(NasiKuning);
        NasiKuning.setText("Nasi Kuning");
        getContentPane().add(NasiKuning, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        btMenu.add(EsJeruk);
        EsJeruk.setText("Es Jeruk");
        getContentPane().add(EsJeruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        btMenu.add(MieAyam);
        MieAyam.setText("Mie Ayam");
        getContentPane().add(MieAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        btMenu.add(Chocolate);
        Chocolate.setText("Chocolate");
        Chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocolateActionPerformed(evt);
            }
        });
        getContentPane().add(Chocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        btMenu.add(AyamGeprek);
        AyamGeprek.setText("Ayam Geprek ");
        getContentPane().add(AyamGeprek, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        btMenu.add(CookiesOreo);
        CookiesOreo.setText("Cookies Oreo");
        getContentPane().add(CookiesOreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        btMenu.add(KentangGoreng);
        KentangGoreng.setText("Kentang Goreng");
        getContentPane().add(KentangGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        btMenu.add(CirengCrispy);
        CirengCrispy.setText("Cireng Crispy");
        CirengCrispy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirengCrispyActionPerformed(evt);
            }
        });
        getContentPane().add(CirengCrispy, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Beli");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 30));

        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 30));

        btnKurang.setText("-");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });
        getContentPane().add(btnKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 40, 30));

        tfJumlahPesan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfJumlahPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 140, 50));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Informasi Pesanan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 20));

        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });
        getContentPane().add(btnBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 60, 30));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 70, 30));

        jLabel8.setText("Pesanan Anda");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 90, 20));

        jLabel9.setText("Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 90, 20));

        jLabel10.setText("Jumlah Pesanan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 90, 20));
        getContentPane().add(tfPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 90, -1));
        getContentPane().add(tfHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 90, -1));
        getContentPane().add(tfJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 90, -1));

        jLabel11.setText("Total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 90, 20));
        getContentPane().add(tfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 90, -1));

        jLabel7.setText(":");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 10, -1));

        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 10, -1));

        jLabel13.setText(":");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 10, -1));

        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 10, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\Baground pemvis\\bg.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NasiGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NasiGorengActionPerformed

    private void CirengCrispyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirengCrispyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CirengCrispyActionPerformed

    private void ChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChocolateActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(tfJumlahPesan.getText());
            jumlah++;
            tfJumlahPesan.setText(Integer.toString(jumlah));
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(tfJumlahPesan.getText());
        if (jumlah > 0) {
            jumlah--;
           tfJumlahPesan.setText(Integer.toString(jumlah));
        }
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
    String pesanan = "";
    int harga = 0;
    boolean menuDipilih = false;

    if (NasiGoreng.isSelected()) {
        pesanan = "Nasi Goreng";
        harga = 12000;
        menuDipilih = true;
    } else if (NasiKuning.isSelected()) {
        pesanan = "Nasi Kuning";
        harga = 10000;
        menuDipilih = true;
    } else if (MieAyam.isSelected()) {
        pesanan = "Mie Ayam";
        harga = 8000;
        menuDipilih = true;
    } else if (AyamGeprek.isSelected()) {
        pesanan = "Ayam Geprek";
        harga = 10000;
        menuDipilih = true;
    } else if (EsTeh.isSelected()) {
        pesanan = "Es Teh";
        harga = 5000;
        menuDipilih = true;
    } else if (EsJeruk.isSelected()) {
        pesanan = "Es Jeruk";
        harga = 8000;
        menuDipilih = true;
    } else if (Chocolate.isSelected()) {
        pesanan = "Chocolate";
        harga = 8000;
        menuDipilih = true;
    } else if (CookiesOreo.isSelected()) {
        pesanan = "Cookies Oreo";
        harga = 10000;
        menuDipilih = true;
    } else if (KentangGoreng.isSelected()) {
        pesanan = "Kentang Goreng";
        harga = 10000;
        menuDipilih = true;
    } else if (CirengCrispy.isSelected()) {
        pesanan = "Cireng Crispy";
        harga = 6000;
        menuDipilih = true;
    }
    
    int jumlah = Integer.parseInt(tfJumlahPesan.getText());

    if (menuDipilih && jumlah > 0) {
        int totalHarga = harga * jumlah;
        tfTotal.setText("Rp" + totalHarga);
        tfPesanan.setText(pesanan);
        tfHarga.setText("Rp" + Integer.toString(harga));
        tfJumlah.setText(Integer.toString(jumlah));
    } else {
        JOptionPane.showMessageDialog(null, "Pilih pesanan terlebih ", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }


    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        btMenu.clearSelection();
        tfJumlahPesan.setText("0");
        tfPesanan.setText("");
        tfJumlah.setText("");
        tfTotal.setText("");
        tfHarga.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AyamGeprek;
    private javax.swing.JRadioButton Chocolate;
    private javax.swing.JRadioButton CirengCrispy;
    private javax.swing.JRadioButton CookiesOreo;
    private javax.swing.JRadioButton EsJeruk;
    private javax.swing.JRadioButton EsTeh;
    private javax.swing.JRadioButton KentangGoreng;
    private javax.swing.JRadioButton MieAyam;
    private javax.swing.JRadioButton NasiGoreng;
    private javax.swing.JRadioButton NasiKuning;
    private javax.swing.ButtonGroup btMenu;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfJumlahPesan;
    private javax.swing.JTextField tfPesanan;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
