/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project2;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Soal1 extends javax.swing.JFrame {

    /**
     * Creates new form Soal1
     */
    public Soal1() {
        initComponents();
        tfTarif.setText("10000");
        tfPotongan.setText("10%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        tfGajiBruto = new javax.swing.JTextField();
        btnTotalGaji = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfJamKerja = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTarif = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfGajiBersih = new javax.swing.JTextField();
        tfPotongan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GAJI KARYAWAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        jLabel3.setText("Jumlah Jam Kerja 1Minggu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        jLabel4.setText("Tari Per-jam");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 30));

        jLabel5.setText("Gaji Bruto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 60, 30));

        btnHitung.setBackground(new java.awt.Color(200, 255, 180));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 70, 30));

        tfGajiBruto.setEditable(false);
        getContentPane().add(tfGajiBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 140, 30));

        btnTotalGaji.setBackground(new java.awt.Color(200, 255, 180));
        btnTotalGaji.setText("Total");
        btnTotalGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalGajiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotalGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 70, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(":");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 10, 30));
        getContentPane().add(tfJamKerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(":");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 10, 30));

        tfTarif.setEditable(false);
        getContentPane().add(tfTarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 140, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(":");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 10, 30));

        jLabel13.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Gaji Bersih ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Gaji Awal");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel11.setText("Potongan Pajak");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 86, -1));

        jLabel6.setText("Total Gaji Bersih");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(":");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 10, 30));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 10, 30));

        tfGajiBersih.setEditable(false);
        getContentPane().add(tfGajiBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 120, 30));

        tfPotongan.setEditable(false);
        tfPotongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPotonganActionPerformed(evt);
            }
        });
        getContentPane().add(tfPotongan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 502, 120, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\Baground pemvis\\Bg total.png")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 320, 170));

        btnReset.setBackground(new java.awt.Color(200, 255, 180));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\Baground pemvis\\Bg desain.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        double gajiBruto;
        String jamKerjaStr = tfJamKerja.getText();
        if (jamKerjaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jam kerja harus diisi.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            double jamKerja = Double.parseDouble(jamKerjaStr);

        if (jamKerja < 0) {
            JOptionPane.showMessageDialog(this, "Jam kerja harus bilangan positif.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            String tarifStr = tfTarif.getText();
            if (tarifStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tarif harus diisi.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            } else {
                double tarif = Double.parseDouble(tarifStr);
                if (jamKerja <= 40) {
                    gajiBruto = jamKerja * tarif;
                } else {
                    double jamLembur = jamKerja - 40;
                    gajiBruto = (40 * tarif) + (jamLembur * (1.5 * tarif));
                }

                tfGajiBruto.setText(String.valueOf(gajiBruto));
            }
        }
    }

    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnTotalGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalGajiActionPerformed
        // TODO add your handling code here:
        double gajiBruto = Double.parseDouble(tfGajiBruto.getText());

        // Hitung potongan pajak (10% dari gaji bruto)
        double potonganPajak = 0.10 * gajiBruto;

        // Hitung gaji bersih (gaji bruto - potongan pajak)
        double gajiBersih = gajiBruto - potonganPajak;

        // Set nilai gaji bersih ke komponen teks eGajibersih
        tfGajiBersih.setText(String.valueOf(gajiBersih));
    }//GEN-LAST:event_btnTotalGajiActionPerformed

    private void tfPotonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPotonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPotonganActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfJamKerja.setText(" ");
        tfGajiBruto.setText(" ");
        tfGajiBersih.setText(" ");
    
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotalGaji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfGajiBersih;
    private javax.swing.JTextField tfGajiBruto;
    private javax.swing.JTextField tfJamKerja;
    private javax.swing.JTextField tfPotongan;
    private javax.swing.JTextField tfTarif;
    // End of variables declaration//GEN-END:variables
}
